In [1]:
import torch

# TENSOR
* Multi-dimentional matrix with elements of single data type 
* Default data type float32

# List

In [2]:
x = [1,2,3, [4,5,6]]
x

[1, 2, 3, [4, 5, 6]]

# Numpy array

In [3]:
import numpy as np

np1 = np.random.rand(3,4)
np1.dtype

dtype('float64')

# Tensor

In [4]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [5]:
tensor_3d = torch.randn(3,4,5)
tensor_3d

tensor([[[ 2.2475, -0.0219,  0.0731, -1.1199,  0.2999],
         [-0.9120,  0.4408,  1.2312,  1.2717, -0.4889],
         [ 0.5211, -0.9870, -0.1438,  0.5587,  1.4799],
         [ 0.3198,  0.1957, -1.5325,  0.9343,  1.4052]],

        [[-0.9129, -0.3203, -0.5311,  0.8088, -0.9886],
         [-1.4191, -1.0797,  0.4959,  0.3127,  0.4009],
         [ 0.2235, -0.5536, -1.0204,  2.5255,  1.3619],
         [-0.5870, -2.4673, -0.1339, -0.3227,  0.5946]],

        [[ 1.6459, -2.4507, -0.7600,  0.1365,  1.8795],
         [ 1.2085,  0.4182, -0.7404, -2.4403, -0.6384],
         [-0.2809,  0.2860,  0.5554, -0.0694, -0.7199],
         [ 1.6736,  0.1851, -0.4308, -0.4654,  0.2693]]])

In [6]:
m_tensor = torch.tensor(np1)
m_tensor

tensor([[0.3472, 0.1817, 0.3712, 0.4420],
        [0.1680, 0.3126, 0.0894, 0.2785],
        [0.2449, 0.8875, 0.1905, 0.7945]], dtype=torch.float64)

# TENSOR OPERATIONS

In [7]:
import torch

In [8]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
# Reshape if we do not know the number of items
my_torch2 = torch.arange(10)
my_torch2 = my_torch2.reshape(-1,2)
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [11]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
# Diffs between shape and view?
# TODO:: Google

In [14]:
# When changing an item within parent tensor the child changes as well 
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [17]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [18]:
# Slices - section of tensor
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Specific item
my_torch7[7]

tensor(7)

In [20]:
# Slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [21]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [22]:
# Return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# TENSOR MATH OPERATIONS

In [23]:
import torch
import numpy as np

In [24]:
t_a = torch.tensor([1,2,3,4])
t_b = torch.tensor([5,6,7,8])

In [25]:
# Addition
t_a+t_b  # Shorthand
# torch.add(t_a,t_b)  # Longhand

tensor([ 6,  8, 10, 12])

In [26]:
# Subtract
t_b - t_a # Shorthand
# torch.sub(t_b, t_a)  # Longhand

tensor([4, 4, 4, 4])

In [27]:
# Multiplication
t_a*t_b  # Shorthand
# torch.mul(t_a,t_b)  # Longhand

tensor([ 5, 12, 21, 32])

In [28]:
# Division
t_b / t_a # Shorthand
# torch.div(t_b,t_a)  # Longhand

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [29]:
# Modulus
t_b % t_a  # Shorthand
# torch.remainder(t_b,t_a)  # Longhand

tensor([0, 0, 1, 0])

In [30]:
# Power
t_a ** t_b  # Shorthand
# torch.pow(t_a,t_b)  # Longhand

tensor([    1,    64,  2187, 65536])

In [31]:
# Another longhand format
t_a.add(t_b)

tensor([ 6,  8, 10, 12])

In [32]:
# Reassignment
t_a + t_b

tensor([ 6,  8, 10, 12])

In [33]:
t_a

tensor([1, 2, 3, 4])

In [34]:
t_a = t_a + t_b  # Long format reassignment
t_a

tensor([ 6,  8, 10, 12])

In [35]:
t_a.add_(t_b)  # Short format reassignment
t_a

tensor([11, 14, 17, 20])